### ISSUE TITLE
[QUESTION]: esbuild minify

### ISSUE THREAD

**Issue by simplecommerce** [nitedani/vite-plugin-standalone#2]
Hi,

I noticed that in the files bundled by esbuild don't seem to be minified.
Do you think it should be on by default or togglable via the options?

Thanks.

**Comment by nitedani** [comment]
I'll expose the esbuild options. I think we shouldn't enable minification by default, because it would make debugging errors harder. The bundled code is meant to be run on the server, where bundle size usually isn't a concern.

**Comment by simplecommerce** [comment]
@nitedani Hi, do you think you'll have time to expose the esbuild options any time soon? I know you must be busy.

Thanks!

**Comment by nitedani** [comment]
@simplecommerce Sorry for the delay, released in 1.0.9

**Comment by nitedani** [comment]
You can pass `esbuild` object to the plugin and override anything

**Comment by nitedani** [comment]
The plugin doesn't support splitting common imports of multiple entries yet, instead creates separate standalone bundles for the entries. I will add the splitting feature soon(or better said - fix the bug that makes it unsupported), that can reduce the size of the output if there are common imports in multiple entries.

**Comment by simplecommerce** [comment]
> You can pass `esbuild` object to the plugin and override anything

Thank you, I will test it soon!

**UPDATE:** Works great, my test package went from 17 to 10 mb, awesome, thanks again!
I'll keep an eye out for the other fix. Appreciate it!
